FROM python:3.9

WORKDIR /app

COPY requirements_base.txt requirements_gpu.txt check_gpu.py install_requirements.sh ./
RUN pip install -r requirements_base.txt
RUN python check_gpu.py

COPY scraper.py scraper_server.py ./

CMD ["uvicorn", "scraper_server:app", "--host", "0.0.0.0", "--port", "8000"]